---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        exclude: ^(.*\.gif|tree-sitter-souffle/src/.*)$
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--unittest]
        exclude: ^tests/util/.*$
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.3
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
        exclude: ^tree-sitter-souffle/(bindings/.*|binding\.gyp|setup\.py)$

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        exclude: ^tree-sitter-souffle/(bindings/.*|binding\.gyp|setup\.py)$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        exclude: ^tree-sitter-souffle/(bindings/.*|binding\.gyp|setup\.py)$

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: ^tree-sitter-souffle/(bindings/.*|binding\.gyp|setup\.py)$

  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
