name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-souffle-analyzer:
    uses: nathanwn/workflows/.github/workflows/tox.yml@3654b0bc8b591f0b6ef0deae901a8645ed9330c7  # v0.5.0
    with:
      os: '["ubuntu-latest", "windows-latest", "macos-latest"]'
      env: '["py38", "py39", "py310", "py311", "py312", "pre-commit"]'

  test-vscode-extension:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: vscode
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run lint
      - run: npm run compile
      # TODO(nathanwn): Figure out how to run e2e tests on GitHub Actions.
      # - run: npm run test
